### ISSUE TITLE
Adding Comment Issue

### ISSUE THREAD

**Issue by PluginDistrict** [dtbaker/support-hub#9] opened 2015-09-01 17:00 UTC
Hi Dave,

I followed the instructions to create a new account plugindistrict_support, and I copied the cookie to the settings, saved and reconnected.  I've also added that account to the author teams for plugindistrict.  when I try to add a comment with support hub it is erroring out.  See screenshot.
![error-comments](https://cloud.githubusercontent.com/assets/6620391/9610751/151b8fe4-50a1-11e5-8d56-1b973b09f064.png)

**Comment by dtbaker** [comment] 2015-09-01 20:53
Thanks I'll setup a brand new account and try it again here shortly

Sent from my phone

**Comment by PluginDistrict** [comment] 2015-09-01 22:44
Ok, thanks Dave.  If it helps, I was logged in as plugindistrict and not plugindistrict_support at the time.  I was able to get it to work once by logging in as support, capturing and updating the cookie data and immediately adding a comment.  But as soon as I switched to my main account it didn’t work.  Should I just change it to use my main account instead?

Thanks for the help and for this super awesome plugin!  It’s should help manage support request as they come in for sure…

**Comment by dtbaker** [comment] 2015-09-01 23:05
You can use the main account if you like, it just feels safer to use a
"dummy" support account when there are cookies are stuff involved.

When the API is updated we won't have this problem.

I think the issue is clicking "logout" from the "support" account. This
kills the cookie that was added to Support Hub. You might be able to login
as "support" in another browser and capture the cookie that way (if using
Google chrome incognito mode you'll have to use dev console to capture
cookie as it won't show up in the main cookie list) and just leave that
browser logged in.

(Or just use main account cookie)

I'll be on a computer in a couple of hours to test and confirm.

**Comment by wpexplorer** [comment] 2015-09-07 02:00
Do you know by chance when Envato intends on updating the API?

**Comment by dtbaker** [comment] 2015-09-07 02:03
@wpexplorer nah - when I was in the office I had a chat to the API team and it's certainly something they are planning. Moving to the new API framework was one of the key steps towards adding new cool stuff like replying to comments. Hopefully once this item is up and running it'll put a bit of pressure on them :)

**Comment by wpexplorer** [comment] 2015-09-07 17:56
Ya, it's a bit ridiculous how impossible it is for authors to provide support via TF...

**Closed as completed** 2015-09-10 12:23 UTC
